### ISSUE TITLE
no module 

### ISSUE THREAD

**Issue by iamkishann** [4rqm/dhooks#3]
ur examples say 
from discordWebhooks import Webhook
while readme says 
from discord_hooks import Webhook

I tried both sudo pip install discordWebhooks and 
pip install discord_hooks
yes I have tried cloning in and installing discordhooks.py but same error when i try to run a example No module named discordhooks (mac)
none seem to work can u help 

Thx

**Comment by shtabbbe** [comment]
There is not setup.py file inside the repo, which means it cannot be installed with pip any way. To install this you should download the file itself and place it in your bots directory

**Comment by 4rqm** [comment]
I'll be uploading a rewritten version to pypi soon.

**Comment by kyb3r** [comment]
Done
