### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by TheLovinator1** [4rqm/dhooks#7]
Hi,
Can you add a license to this project? This project is under copyright right now because you haven't added a license that specifies otherwise. RalphORama (#6) suggested MIT, and it would work perfectly.

**Comment by shtabbbe** [comment]
Sorry @TheLovinator1 this repo is kind of dead, you can make your own webhook library based on this if you want

**Comment by 4rqm** [comment]
Added a licence, a bit late, sorry.
